jobs:
  # Build & Push to Staging
  darkube_build_candofitclub-backend-stage_myprojects-candofitclub_hamravesh-c13:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME_STAGE: registry.hamdocker.ir/myprojects/candofitclub-backed-stage
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      uses: actions/checkout@v4
    - name: darkube-cli build & push for staging
      run: 'darkube build --push -t $IMAGE_NAME_STAGE:${GITHUB_SHA:0:7} -t $IMAGE_NAME_STAGE:${GITHUB_REF_NAME}
        --docker-auth-config ${{secrets.DOCKER_AUTH_CONFIG_STAGE}} --workdir . --file ./Dockerfile
        --build-context . '

  # Build & Push to Production
  darkube_build_candofitclub-backend_myprojects-candofitclub_hamravesh-c13:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME_PROD: registry.hamdocker.ir/myprojects/candofitclub-backed
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      uses: actions/checkout@v4
    - name: darkube-cli build & push for production
      run: 'darkube build --push -t $IMAGE_NAME_PROD:${GITHUB_SHA:0:7} -t $IMAGE_NAME_PROD:${GITHUB_REF_NAME}
        --docker-auth-config ${{secrets.DOCKER_AUTH_CONFIG_PRODUCTION}} --workdir . --file ./Dockerfile
        --build-context . '

  # Deploy to Staging
  darkube_deploy_candofitclub-backend-stage_myprojects-candofitclub_hamravesh-c13:
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_candofitclub-backend-stage_myprojects-candofitclub_hamravesh-c13
    runs-on: ubuntu-latest
    steps:
    - name: darkube-cli deploy to staging
      run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_CANDOFITCLUB_BACKEND_STAGE_MYPROJECTS_CANDOFITCLUB_HAMRAVESH_C13}}
        --app-id ${{secrets.APP_ID_CANDOFITCLUB_BACKEND_STAGE_MYPROJECTS_CANDOFITCLUB_HAMRAVESH_C13}}
        --image-tag ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}
        --server-url ${{secrets.STAGING_SERVER_URL}}

  # Deploy to Production
  darkube_deploy_candofitclub-backend_myprojects-candofitclub_hamravesh-c13:
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_candofitclub-backend_myprojects-candofitclub_hamravesh-c13
    runs-on: ubuntu-latest
    steps:
    - name: darkube-cli deploy to production
      run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_CANDOFITCLUB_BACKEND_MYPROJECTS_CANDOFITCLUB_HAMRAVESH_C13}}
        --app-id ${{secrets.APP_ID_CANDOFITCLUB_BACKEND_MYPROJECTS_CANDOFITCLUB_HAMRAVESH_C13}}
        --image-tag ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}
        --server-url ${{secrets.PRODUCTION_SERVER_URL}}

on:
  push:
    branches:
      - main
      - develop
